### PR TITLE
Use values

### PR DESCRIPTION
**Pull request by Ngorror**
An idea how to extend this library with dynamically generated values by key.

With some overcomplicated initialization process of the values by providing Object or Array of Two-dimensional Arrays

we have `createValuesContainer(initialEntries, strict)` method

and `useValues(valuesContainer, key, initialValue)` hook

`createValuesContainer` param `strict` by default is `false` which will allow future added values via `useValues` hook to be generated and initialized silently

when `strict` is `true` error will be thrown from `useValues` hook because of missing value in the container.

an example with create-react-app was provided in examples directory

### CODE REVIEW

**Comment by kof** [comment]
I don't want to disappoint, but I don't like the proposal so far. If I understand correctly you want to have a fixed keys schema that you want to enforce by passing a schema to the container and making dispatcher throw errors when user is trying to set something they shouldn't.

While I see it as an interesting exercise, I don't see a fit for this task in this library.

**Comment by Ngorror** [comment]
No. this is not the main idea of my proposal.
I'm working on a frontend where we don't have or know upfront any objects and their structure. 
We are receiving "documents" with flexible properties. 
That's why I cannot use your library with predefined in the code resources. 
Here is your example
```js
// value-containers.js
import { createValueContainer } from "react-nano-state";
export const searchContainer = createValueContainer(initialValue);
```
you have only one value linked to your search input box.

I have list of values/documents/objects that I can recognize only by their _id/key and I cannot hardcode them in my value-containers.js

so I'm creating this resource "collection" by integrating your value container in a set with keys.
And because I don't know upfront the name and/or the initial value - I'm initializing it on the firs use of```useValues(resourceContainer, key1, value1)``` in a component.

using the ```strict``` value is just in case someone doesn't want to create resource on-the-fly - then the component will throw an error. I'm adding constantly resources in my valuesContainer and I'm using the module in non-strict mode all the time.

And as a side effect (not a react effect :) )  I'm kind of cheating with my modification because with these keys I can easily turn your valueContainer into an "hidden" cache of resources that I can access from any part of my dynamic frontend and also can continue receiving state updates for each new place where I've attached it into a component.

I overcomplicated the initialization of a resource - via provided Object or Array of Arrays. but again for dynamic resources I don't use it. I just like the idea of flavorful initializator  

Anyway I will try to keep updated my fork in future when you release a new versions.
Thanks for your work and package. It is very useful for me :)

EDIT:
at the end I might use only one centralized valuesContainer in my project and throw away my Application React Context. And I will inject all my resources in this valuesContainer and will access them via key.

**Comment by kof** [comment]
It's certainly an interesting use case, what I am still trying to understand though is what stops you from using objects as a value and access a key on the object as you see the need on the receiver side?

**Comment by Ngorror** [comment]
I will prepare short meaningful example.
I have a good candidate for this. I’m updating react-treebeard (https://github.com/storybookjs/react-treebeard) with my branch and I will be glad to have your comment. 
And maybe a proposal how can I use your idea with only one object as value with your module.

**Comment by kof** [comment]
closing due to inactivity, feel free to reopen

**Pull request closed without merging**
